version: "3.7"

services:

  api:
    container_name: dapur-online-akuntansi-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - traefiknet
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefiknet"
      - "traefik.frontend.rule=Host:dapur-online-akuntansi-api.luqmanul.com"
      - "traefik.port=8081"
      - "traefik.protocol=http"
      - "traefik.frontend.redirect.entryPoint=https"
    environment: 
      - GO_ENV=production
      - DB_HOST=svr-aura.luqmanul.com
      - DB_PORT=3312
      - DB_USER=root
      - DB_PASS=x83zR3wfTNwZ4zGU
      - DB_SCHEMA=dapur_online_akutansi

networks:
  traefiknet:
    driver: bridge
