version: "3.7"

services:

  api:
    container_name: dapur-online-akuntansi-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - traefiknet
      - pgnet
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefiknet"
      - "traefik.frontend.rule=Host:dapur-online-akuntansi-api.luqmanul.com"
      - "traefik.port=8080"
      - "traefik.protocol=http"
      - "traefik.frontend.redirect.entryPoint=https"
    environment: 
      - GO_ENV=production
      - DB_HOST=postgres-dev
      - DB_PORT=5432
      - DB_USER=hakim
      - DB_PASS=x83zR3wfTNwZ4zGU
      - DB_SCHEMA=dapur_online_akutansi
      - DB_PATH=public

networks:
  traefiknet:
    external: true
  pgnet:
    external: true

